name: build-package

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-and-release-package.yml'
      - '.github/workflows/build-package.yml'
      - 'pom.xml'
      - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/build-and-release-package.yml'
      - '.github/workflows/build-package.yml'
      - 'pom.xml'
      - 'src/**'
  workflow_dispatch:

concurrency: build-${{github.ref}}

jobs:
  build-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: 'github'

      - name: Build package and run tests
        run: mvn --batch-mode test

      - name: Deploy to GitHub
        if: github.event_name != 'pull_request'
        run: mvn --batch-mode deploy -DskipTests -Pgithub_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
